version: 2.1

orbs:
  snyk: snyk/snyk@0.0.8

jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    environment:
      GOLANG_VERSION: 1.13.8
      OPERATOR_SDK_VERSION: 0.15.2
      NOTARY_VERSION: 0.6.1
      KUBECTL_VERSION: 1.12.0
      K3D_VERSION: 3.0.0
      GOPATH: /home/circleci/go
      GO111MODULE: "on"
    working_directory: /home/circleci/go/src/github.com/patoarvizu/vault-dynamic-configuration-operator
    steps:
      - checkout
      - restore_cache:
          keys:
            - vault-dynamic-configuration-operator-golang-cache-{{ checksum "go.sum" }}
      - run:
          name: Install golang
          command: |
            sudo rm -rf /usr/local/go
            curl -Lo go.linux-amd64.tar.gz "https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz"
            sudo tar -C /usr/local -xzf go.linux-amd64.tar.gz
            mkdir -p ${HOME}/go/bin
            echo 'export PATH="$GOPATH/bin:$PATH"' >> "${BASH_ENV}"
      - run:
          name: Install operator-sdk
          command: |
            curl -L https://github.com/operator-framework/operator-sdk/releases/download/v${OPERATOR_SDK_VERSION}/operator-sdk-v${OPERATOR_SDK_VERSION}-x86_64-linux-gnu -o ${HOME}/go/bin/operator-sdk
            chmod +x ${HOME}/go/bin/operator-sdk
      - run:
          name: Build image
          command: |
            operator-sdk build patoarvizu/vault-dynamic-configuration-operator:latest
      - save_cache:
          key: vault-dynamic-configuration-operator-golang-cache-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod/cache
      - snyk/scan:
          docker-image-name: patoarvizu/vault-dynamic-configuration-operator:latest
          fail-on-issues: true
          project: patoarvizu/vault-dynamic-configuration-operator
          severity-threshold: low
      - run:
          name: Install kubectl
          command: |
            curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            mkdir -p "${HOME}/.kube"
            touch "${HOME}/.kube/config"
      - run:
          name: Install k3d
          command: |
            wget -q -O - https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v${K3D_VERSION} bash
      - run:
          name: Run all tests
          command: |
            export KUBECONFIG=~/.k3d/k3s-default-config
            k3d cluster create --image rancher/k3s:v1.0.0 --wait --switch-context=false
            k3d image import patoarvizu/vault-dynamic-configuration-operator:latest
            kubectl apply -f https://raw.githubusercontent.com/patoarvizu/common-manifests/master/prometheus-operator/crds.yaml
            kubectl apply -f https://raw.githubusercontent.com/patoarvizu/common-manifests/master/vault/vault-operator.yaml
            kubectl apply -f https://raw.githubusercontent.com/patoarvizu/common-manifests/master/vault/vault-cluster-kubernetes-and-db.yaml
            kubectl apply -f test/manifests/namespaces/test.yaml
            kubectl apply -f deploy/
            operator-sdk test local ./test/e2e/ --namespace "vault" --go-test-flags '-v -run TestMonitoringObjectsCreated'
            operator-sdk test local ./test/e2e/ --namespace "vault" --go-test-flags '-v -run TestSingleNamespace'
            kubectl -n vault patch deployment vault-dynamic-configuration-operator --type='json' -p='[{"op":"add", "path":"/spec/template/spec/containers/0/command/-", "value":"--bound-roles-to-all-namespaces"}]'
            operator-sdk test local ./test/e2e/ --namespace "vault" --go-test-flags '-v -run TestAllNamespaces'
      - run:
          name: Install notary
          command: |
            curl -L https://github.com/theupdateframework/notary/releases/download/v${NOTARY_VERSION}/notary-Linux-amd64 -o notary
            chmod +x notary
            sudo mv notary /usr/local/bin
      - run:
          name: Build operator
          command: |
            docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_ACCESS_TOKEN
            echo $ENCODED_NOTARY_ROLE_KEY | base64 -d > ${HOME}/vault-dynamic-configuration-operator-circleci.key
            export NOTARY_DELEGATION_PASSPHRASE=$NOTARY_ROLE_PASSPHRASE
            notary -s https://notary.docker.io -d ~/.docker/trust key import ${HOME}/vault-dynamic-configuration-operator-circleci.key --role vault-dynamic-configuration-operator-circleci
            export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=$NOTARY_DELEGATION_PASSPHRASE
            OPERATOR_BUILD_ARGS="--build-arg GIT_COMMIT=$CIRCLE_SHA1 --build-arg GIT_TAG=$CIRCLE_TAG --build-arg COMMIT_TIMESTAMP=$(git log -1 --format=%at) --build-arg AUTHOR_EMAIL=$(git log -1 --format=%ae) --build-arg SIGNATURE_KEY=$(git log -1 --format=%GK)"
            operator-sdk build patoarvizu/vault-dynamic-configuration-operator:$CIRCLE_SHA1 --image-build-args "$OPERATOR_BUILD_ARGS"
            export DOCKER_CONTENT_TRUST=1
            VERSION=${CIRCLE_TAG:-latest}
            docker tag patoarvizu/vault-dynamic-configuration-operator:$CIRCLE_SHA1 patoarvizu/vault-dynamic-configuration-operator:latest
            docker tag patoarvizu/vault-dynamic-configuration-operator:$CIRCLE_SHA1 patoarvizu/vault-dynamic-configuration-operator:$VERSION
            docker push patoarvizu/vault-dynamic-configuration-operator:$CIRCLE_SHA1
            docker push patoarvizu/vault-dynamic-configuration-operator:$VERSION
            docker push patoarvizu/vault-dynamic-configuration-operator:latest

workflows:
  version: 2
  build-operator:
    jobs:
      - build:
          context: authentication-tokens
          filters:
            tags:
              only: /^v\d+\.\d+.\d+$/