version: 2.1

jobs:
  build:
    machine:
        enabled: true
        image: circleci/classic:201808-01
    environment:
      GOLANG_VERSION: 1.11.6
      OPERATOR_SDK_VERSION: 0.11.0
      KUBECTL_VERSION: 1.12.0
      K3D_VERSION: 1.3.1
      GOPATH: /home/circleci/go
      GO111MODULE: "on"
    working_directory: /home/circleci/go/src/github.com/patoarvizu/vault-dynamic-configuration-operator
    steps:
      - checkout
      - restore_cache:
          keys:
            - vault-dynamic-configuration-operator-golang-cache-{{ checksum "go.sum" }}
      - run:
          name: Install golang
          command: |
            sudo rm -rf /usr/local/go
            curl -Lo go.linux-amd64.tar.gz "https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz"
            sudo tar -C /usr/local -xzf go.linux-amd64.tar.gz
            mkdir -p ${HOME}/go/bin
            echo 'export PATH="$GOPATH/bin:$PATH"' >> "${BASH_ENV}"
      - run:
          name: Install operator-sdk
          command: |
            curl -L https://github.com/operator-framework/operator-sdk/releases/download/v${OPERATOR_SDK_VERSION}/operator-sdk-v${OPERATOR_SDK_VERSION}-x86_64-linux-gnu -o ${HOME}/go/bin/operator-sdk
            chmod +x ${HOME}/go/bin/operator-sdk
      - run:
          name: Install kubectl
          command: |
            curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            mkdir -p "${HOME}/.kube"
            touch "${HOME}/.kube/config"
      - run:
          name: Install k3d
          command: |
            wget -q -O - https://raw.githubusercontent.com/rancher/k3d/v${K3D_VERSION}/install.sh | bash
      - run:
          name: Build container
          command: |
            operator-sdk build patoarvizu/vault-dynamic-configuration-operator:$CIRCLE_SHA1
      - save_cache:
          key: vault-dynamic-configuration-operator-golang-cache-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod/cache

workflows:
  version: 2
  build-operator:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+.\d+$/