kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-dynamic-configuration-operator
subjects:
- kind: ServiceAccount
  name: vault-dynamic-configuration-operator
  namespace: vault
roleRef:
  kind: ClusterRole
  name: vault-dynamic-configuration-operator
  apiGroup: rbac.authorization.k8s.io