apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-dynamic-configuration
  namespace: vault
data:
  policy-template: |
    path "secret/{{ .Name }}" {
      capabilities = ["read"]
    }
  db-user-creation-statement: "CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}'; GRANT ALL ON *.* TO '{{name}}'@'%';"