apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-dynamic-configuration-operator
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault-dynamic-configuration-operator
  template:
    metadata:
      labels:
        name: vault-dynamic-configuration-operator
    spec:
      serviceAccountName: vault-dynamic-configuration-operator
      containers:
        - name: vault-dynamic-configuration-operator
          # Replace this with the built image name
          image: vault-dynamic-configuration-operator:latest
          command:
          - vault-dynamic-configuration-operator
          - --auto-configure-annotation=vault.patoarvizu.dev/auto-configure
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vault-dynamic-configuration-operator"
