kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-dynamic-configuration-operator
  namespace: vault
subjects:
- kind: ServiceAccount
  name: vault-dynamic-configuration-operator
  namespace: vault
roleRef:
  kind: Role
  name: vault-dynamic-configuration-operator
  apiGroup: rbac.authorization.k8s.io
