kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-dynamic-configuration-operator
  namespace: vault
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch