annotationPrefix: vault.patoarvizu.dev
boundRolesToAllNamespaces: false
imageVersion: latest
imagePullPolicy: IfNotPresent
serviceAccount:
  name: vault-dynamic-configuration-operator
watchNamespace: ""
defaultConfiguration:
  policyTemplate: |
    path "secret/{{ .Name }}" {
      capabilities = ["read"]
    }
  dbUserCreationStatement: "CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}'; GRANT ALL ON *.* TO '{{name}}'@'%';"
  dbDefaultTTL: 1h
  dbMaxTTL: 24h
resources: